### ISSUE TITLE
link to 2021 is broken

### ISSUE THREAD

**Issue by BrunoBonacci** [reclojure/reclojure.github.io#102]
the link http://www.reclojure.org/2021/index.html

returns 404:

![image](https://user-images.githubusercontent.com/1639862/200282223-8dbabe45-5dbd-4eb4-bcf6-b362185941eb.png)

**Comment by oxalorg** [comment]
@reborg I think in this commit we ended up renaming the 2021 snapshot to 2022. https://github.com/reclojure/reclojure.github.io/pull/101/commits/161389acb47213d73e190d147b91e2560305bafa

We didn't need to do that because for the "live" year (i.e. 2022) gh-actions will automatically build from `master` and deploy it to to `gh-pages`. We only need to manually snapshot the older years.

**Comment by oxalorg** [comment]
I'll create a PR to fix this
